language: cpp
script:
  - mkdir build && cd build && cmake .. && make && ./tests/tests/yunomi_tests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-7
      - libhdf5-dev