#ifndef YUNOMI_DEFINES_H_
#define YUNOMI_DEFINES_H_

#define FIB_ENCODER_NOTFOUND ((size_t)-1)

#define UINT64_T_SIZE 64
#define UINT64_T_SIZE_BITS 6
#define UINT64_T_SIZE_MASK 0x3FULL

#endif //YUNOMI_DEFINES_H_

